### PR TITLE
Auto, Random and Safe Port choosing

### PR DESCRIPTION
**Pull request by mohoshakeri**
I was using it when I noticed a problem.
If port **8000** was busy with another service, it would fail.

At first I tried to leave the port selection process to the **user**.
But I noticed that you get single executable files as output from this source code. I decided to make the port selection **automatic** and **random** from **free ports**.

### CODE REVIEW

**Comment by aminupy** [comment]
Hi @mohoshakeri,

Thank you for your contribution and the effort you've put into this feature! I appreciate your attention to detail and your support for the project.

Could you please update your pull request to target the develop branch instead of the main branch? Once you've created the new pull request, you can close this one. Let me know if you need any assistance with the process.

Thanks again for your contribution! Looking forward to reviewing your updated PR.

**Comment by mohoshakeri** [comment]
Hi @aminupy 

I applied the change you wanted.

**Review by aminupy — APPROVED** [review]
seems good to prevent running the app on busy ports.

**Comment by aminupy** [comment]
@mohoshakeri thank you for your collaboration.

**Pull request merged**
